name: QA_Test_API_Disciple v2

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : Install Newman
        run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra
      - name: Make directory for results
        run: mkdir -p TestResults
      - name: Run API tests
        run: |
          newman run /.github/workflows/test.json --reporters cli,htmlextra --reporter-htmlextra-export TestResults/HtmlReport.html
      
