name: QA_Test_API_Disciple v2

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3.6.0
        with: 
          node-version: '16.x'
      - name : Install Newman
        run: |
              npm install -g newman
              npm install -g newman-reporter-slackreporter
              npm install -g newman-reporter-htmlextra
      - name: Make directory for results
        run: mkdir -p TestResults
      - name: Run API tests
        run: |
          newman run dis/test.json -e dis/test_envi.json --reporters cli,htmlextra --reporter-htmlextra-export TestResults/HtmlReport.html
      - name : Upload report
        uses : actions/upload-artifact@v3.1.2
        with:
          name : report
          path : TestResults
